[env]
TERM = "xterm-256color"

[shell]
program = "zellij"

[window]
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 0.97

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
