[colors.bright]
black = "#100F0F"
blue = "#205EA6"
cyan = "#3AA99F"
green = "#879A39"
magenta = "#CE5D97"
red = "#D14D41"
white = "#FFFCF0"
yellow = "#D0A215"

[colors.cursor]
cursor = "#100F0F"
text = "#FFFCF0"

[colors.dim]
black = "#100F0F"
blue = "#205EA6"
cyan = "#3AA99F"
green = "#879A39"
magenta = "#CE5D97"
red = "#D14D41"
white = "#FFFCF0"
yellow = "#D0A215"

[colors.normal]
black = "#100F0F"
blue = "#205EA6"
cyan = "#3AA99F"
green = "#879A39"
magenta = "#CE5D97"
red = "#D14D41"
white = "#FFFCF0"
yellow = "#D0A215"

[colors.primary]
background = "#FFFCF0"
bright_foreground = "#100F0F"
dim_foreground = "#100F0F"
foreground = "#100F0F"
